name: CI

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  test:
    name: Test on Erlang/OTP ${{matrix.otp}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp:
          - '21.0'
          - '21.3'
          - '22.0'
          - '24.2'
        include:
          - otp: '21.0'
            rebar: '3.15.2'
          - otp: '21.3'
            rebar: '3.15.2'
          - otp: '22.0'
            rebar: '3.18.0'
          - otp: '24.2'
            rebar: '3.18.0'
      fail-fast: false
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install libyaml-dev
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cache Rebar data
        uses: actions/cache@v2
        with:
          path: ~/.cache/rebar3
          key: ${{runner.os}}-${{matrix.otp}}-${{matrix.rebar}}-${{hashFiles('rebar.config')}}
      - name: Download Erlang/OTP ${{matrix.otp}} and Rebar ${{matrix.rebar}}
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar}}
          version-type: strict
      # Until https://github.com/erlware/relx/issues/905 is fixed:
      - name: Create Erlang cookie
        run: erl -noinput -sname cookie -eval 'halt()'
      - name: Download previous test results
        run: |
          mkdir -p _build/test
          curl -sSL https://github.com/weiss/eturnal/tarball/gh-pages |
            tar -C _build/test --strip-components=1 --wildcards -xzf - '*/logs/'
      - name: Download dependencies
        run: rebar3 get-deps
      - name: Compile code
        run: rebar3 compile
      - name: Build release
        run: rebar3 release
      - name: Start release
        run: _build/default/rel/eturnal/bin/eturnal daemon
      - name: Ping release
        run: _build/default/rel/eturnal/bin/eturnal ping
      - name: Stop release
        run: _build/default/rel/eturnal/bin/eturnal stop
      - name: Analyze cross references
        run: rebar3 xref
      - name: Perform static code analysis
        run: rebar3 dialyzer
      - name: Run test suite
        run: rebar3 ct
      - name: Check test coverage
        run: rebar3 cover
      - name: Upload test and coverage results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: eturnal-tests-otp-${{matrix.otp}}
          #
          # Appending the wildcard character ("*") is a trick to make "test" the
          # root directory of the uploaded ZIP file:
          #
          # https://github.com/actions/upload-artifact#upload-using-multiple-paths-and-exclusions
          #
          path: |
            _build/test*/logs
            _build/test*/cover
  publish:
    name: Publish test results
    runs-on: ubuntu-latest
    needs: test
    if: github.ref_name == 'master' && github.repository_owner == 'weiss' && always()
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Retrieve test and coverage results
        uses: actions/download-artifact@v2
        with:
          name: eturnal-tests-otp-24.2
          path: public
      - name: Deploy test and coverage results to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: ci.eturnal.net
          publish_dir: public/test
          github_token: ${{secrets.GITHUB_TOKEN}}
